# Generated by Django 4.2.1 on 2023-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='lienCv',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='telephone',
        ),
        migrations.AddField(
            model_name='demande',
            name='message',
            field=models.CharField(default='', max_length=2000, verbose_name='Message'),
        ),
    ]
