# Generated by Django 4.2.1 on 2023-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0002_remove_demande_liencv_remove_demande_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='telephone',
            field=models.CharField(default='', max_length=20, verbose_name='Telephone'),
        ),
    ]
