# Generated by Django 4.2.1 on 2023-06-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(default='', max_length=100, verbose_name='Nom de produit')),
                ('client', models.CharField(default='', max_length=100, verbose_name='Client')),
                ('status', models.CharField(default='', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
